steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/cinema-project:$COMMIT_SHA', '.']
    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/cinema-project:$COMMIT_SHA']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - 'cinema-project'
          - '--image'
          - 'gcr.io/$PROJECT_ID/cinema-project:$COMMIT_SHA'
          - '--region'
          - 'europe-north1 (Finland)'
    - images:
          - 'gcr.io/$PROJECT_ID/cinema-project:$COMMIT_SHA'
