export const makes = [
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "DS",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "LYNK & CO",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Renault",
  "Rolls Royce",
  "Rover",
  "Saab",
  "Seat",
  "Skoda",
  "Smart",
  "Ssang Yong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Other",
];

export const models = {
  "Alfa Romeo": [
    "147",
    "156",
    "159",
    "4C",
    "Brera",
    "Giulia",
    "Giulietta",
    "GT",
    "MiTo",
    "Spider",
    "Stelvio",
  ],
  "Aston Martin": [
    "DB7",
    "DB9",
    "DB11",
    "DBS",
    "DBS Superleggera",
    "One-77",
    "Rapide",
    "Vanquish",
    "V12 Vantage",
    "V8 Vantage",
    "Vantage",
    "Virage",
  ],
  Audi: [
    "A3",
    "A4",
    "A6",
    "A8",
    "E-tron",
    "Q3",
    "Q4 E-tron",
    "Q5",
    "Q7",
    "R8",
    "S3",
    "S4",
    "S5",
    "S6",
    "S8",
    "TT",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
  ],
  Bentley: ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  BMW: [
    "3 Series",
    "5 Series",
    "7 Series",
    "8 Series",
    "M3",
    "M4",
    "M5",
    "M6",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "i8",
    "iX",
  ],
  Bugatti: ["Chiron", "Veyron"],
  BYD: ["Atto 3"],
  Cadillac: ["ATS", "CTS", "Escalade", "XTS"],
  Chevrolet: [
    "Camaro",
    "Corvette",
    "Equinox",
    "Impala",
    "Malibu",
    "Suburban",
    "Tahoe",
    "Traverse",
  ],
  Chrysler: ["300C", "Voyager"],
  Citroën: [
    "Berlingo",
    "C3",
    "C4",
    "C5",
    "C6",
    "DS3",
    "DS4",
    "DS5",
    "Xsara Picasso",
  ],
  Cupra: ["Ateca", "Born", "Formentor", "Leon"],
  Dacia: ["Duster", "Logan", "Sandero"],
  Daewoo: ["Lanos", "Matiz", "Nubira"],
  Daihatsu: ["Cuore", "Sirion", "Terios"],
  Dodge: ["Challenger", "Charger", "Durango", "Ram"],
  DS: ["DS 3", "DS 4", "DS 5"],
  Ferrari: [
    "458 Italia",
    "488 GTB",
    "California",
    "FF",
    "F430",
    "LaFerrari",
    "Portofino",
    "812 Superfast",
  ],
  Fiat: [
    "124 Spider",
    "500",
    "500L",
    "500X",
    "Bravo",
    "Doblo",
    "Panda",
    "Tipo",
    "Qubo",
  ],
  Ford: [
    "Edge",
    "Escape",
    "Explorer",
    "F-150",
    "Fiesta",
    "Focus",
    "Kuga",
    "Mondeo",
    "Mustang",
    "Ranger",
  ],
  GMC: ["Canyon", "Sierra", "Yukon"],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Fit",
    "HR-V",
    "Odyssey",
    "Pilot",
    "Ridgeline",
  ],
  Hummer: ["H2", "H3"],
  Hyundai: [
    "i10",
    "i20",
    "i30",
    "i40",
    "IONIQ",
    "Kona",
    "Nexo",
    "Palisade",
    "Santa Fe",
    "Tucson",
  ],
  Infiniti: ["Q50", "Q60", "Q70", "QX30", "QX50", "QX60", "QX80"],
  Isuzu: ["D-Max", "MUX", "Trooper"],
  Iveco: ["Daily", "Eurocargo", "Stralis"],
  Jaguar: ["E-PACE", "F-PACE", "I-PACE", "XE", "XF", "XJ"],
  Jeep: ["Cherokee", "Compass", "Grand Cherokee", "Renegade", "Wrangler"],
  Kia: [
    "Ceed",
    "EV6",
    "EV7",
    "EV9",
    "Niro",
    "Optima",
    "Picanto",
    "Rio",
    "Sorento",
    "Soul",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  Koenigsegg: ["Agera", "CCX", "Jesko", "Regera"],
  Lada: ["Granta", "Kalina", "Niva", "Priora", "Vesta"],
  Lamborghini: ["Aventador", "Huracan", "Urus"],
  Lancia: ["Delta", "Ypsilon"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Evoque",
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: ["ES", "GS", "IS", "LC", "LX", "NX", "RX", "UX"],
  Lincoln: ["Continental", "MKZ", "Navigator"],
  Lotus: ["Elise", "Evora", "Exige"],
  "LYNK & CO": ["01", "02", "03", "05"],
  Maserati: ["Ghibli", "GranTurismo", "Levante", "MC20", "Quattroporte"],
  Maybach: ["57", "62"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "MX-5"],
  McLaren: ["540C", "570S", "600LT", "620R", "675LT", "720S", "765LT", "GT"],
  "Mercedes-Benz": [
    "A-Class",
    "AMG GT",
    "B-Class",
    "C-Class",
    "CLA",
    "CLS",
    "E-Class",
    "EQA",
    "EQB",
    "EQE",
    "EQS",
    "G-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "M-Class",
    "S-Class",
    "SL",
    "SLC",
    "V-Class",
    "X-Class",
  ],
  MG: ["Marvel R", "MG3", "MG4", "MG5", "MG ZS"],
  Mini: ["Clubman", "Cooper", "Convertible", "Countryman", "Paceman"],
  Mitsubishi: [
    "ASX",
    "Eclipse Cross",
    "Lancer",
    "Outlander",
    "Pajero",
    "Space Star",
  ],
  Nissan: ["Juke", "Leaf", "Micra", "Note", "Qashqai", "X-Trail"],
  Opel: ["Astra", "Corsa", "Insignia", "Mokka", "Zafira"],
  Peugeot: ["2008", "208", "3008", "308", "5008"],
  Polestar: ["Polestar 1", "Polestar 2"],
  Pontiac: ["GTO", "Grand Prix", "Solstice"],
  Porsche: [
    "911",
    "Boxster",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  Renault: ["Captur", "Clio", "Kadjar", "Megane", "Scenic", "Talisman"],
  "Rolls Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
  Rover: ["25", "45", "75"],
  Saab: ["9-3", "9-5"],
  Seat: ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"],
  Skoda: ["Enyaq", "Citigo", "Fabia", "Karoq", "Kodiaq", "Octavia", "Superb"],
  Smart: ["Forfour", "Fortwo"],
  "Ssang Yong": ["Korando", "Musso", "Rexton", "Tivoli"],
  Subaru: ["Forester", "Impreza", "Legacy", "Outback", "XV"],
  Suzuki: ["Baleno", "Jimny", "S-Cross", "Swift", "Vitara"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "Aygo",
    "Aygo X",
    "BZ4X",
    "C-HR",
    "Camry",
    "Corolla",
    "Corolla Cross",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Yaris",
    "Yaris Cross",
  ],
  Volkswagen: [
    "Arteon",
    "Golf",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID. Buzz",
    "Multivan",
    "Passat",
    "Polo",
    "Taigo",
    "Tiguan",
    "Touareg",
    "Up!",
  ],
  Volvo: ["S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC70", "XC90"],
  Other: ["Other"],
};
